import streamlit as st
from pathlib import Path
import google.generativeai as genai
import base64
import os
from dotenv import load_dotenv
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from io import BytesIO
from datetime import datetime

# Load environment variables
load_dotenv()

# Function to generate PDF report
def generate_pdf_report(report_text, patient_info="Anonymous", filename="medical_report.pdf"):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1*inch)
    
    # Get styles
    styles = getSampleStyleSheet()
    
    # Create custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.darkgreen,
        spaceAfter=30,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    header_style = ParagraphStyle(
        'CustomHeader',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.darkblue,
        spaceBefore=20,
        spaceAfter=12,
        fontName='Helvetica-Bold'
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=11,
        alignment=TA_JUSTIFY,
        spaceBefore=6,
        spaceAfter=6,
        leftIndent=20,
        rightIndent=20
    )
    
    info_style = ParagraphStyle(
        'InfoStyle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.gray,
        alignment=TA_CENTER,
        spaceBefore=10,
        spaceAfter=10
    )
    
    # Build the PDF content
    story = []
    
    # Title
    story.append(Paragraph("🏥 MEDICAL REPORT ANALYSIS", title_style))
    story.append(Spacer(1, 12))
    
    # Report info
    current_time = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    story.append(Paragraph(f"Generated on: {current_time}", info_style))
    story.append(Paragraph(f"Patient: {patient_info}", info_style))
    story.append(Spacer(1, 20))
    
    # Report content header
    story.append(Paragraph("📋 AI-Generated Medical Analysis", header_style))
    story.append(Spacer(1, 12))
    
    # Process and add report text
    # Split the report into paragraphs and format them
    paragraphs = report_text.split('\n')
    for para in paragraphs:
        if para.strip():
            # Check if it's a header (starts with ** or contains certain keywords)
            if para.strip().startswith('**') and para.strip().endswith('**'):
                # Remove ** and make it a header
                header_text = para.strip().replace('**', '')
                story.append(Paragraph(header_text, header_style))
            elif any(keyword in para.lower() for keyword in ['assessment:', 'findings:', 'recommendation:', 'impression:', 'diagnosis:']):
                story.append(Paragraph(para, header_style))
            else:
                story.append(Paragraph(para, body_style))
            story.append(Spacer(1, 6))
    
    # Footer
    story.append(Spacer(1, 30))
    story.append(Paragraph("⚠️ IMPORTANT DISCLAIMER", header_style))
    disclaimer = """
    This analysis is generated by AI and is for informational purposes only. 
    It should not replace professional medical diagnosis or treatment. 
    Please consult with a qualified healthcare provider for proper medical evaluation and advice.
    """
    story.append(Paragraph(disclaimer, info_style))
    
    story.append(Spacer(1, 20))
    story.append(Paragraph("🤖 Developed by Sankalp | Medical AI Assistant", info_style))
    
    # Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer

# Function to load and encode background image
def get_base64_of_bin_file(bin_file):
    with open(bin_file, 'rb') as f:
        data = f.read()
    return base64.b64encode(data).decode()

# Function to set background image
def set_png_as_page_bg(png_file):
    bin_str = get_base64_of_bin_file(png_file)
    page_bg_img = f'''
    <style>
    .stApp {{
        background-image: url("data:image/jpg;base64,{bin_str}");
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        background-attachment: fixed;
    }}
    
    /* Make the main content container darker */
    .main .block-container {{
        background-color: rgba(0, 0, 0, 0.85) !important;
        border-radius: 15px;
        padding: 2rem;
        margin-top: 2rem;
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.4);
        border: 2px solid #4CAF50;
        color: white !important;
    }}
    
    /* Style the title */
    .main .block-container h1 {{
        color: #4CAF50 !important;
        text-align: center;
        text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
        border-bottom: 3px solid #4CAF50;
        padding-bottom: 1rem;
        margin-bottom: 2rem;
    }}
    
    /* Style all text elements */
    .main .block-container p, .main .block-container div {{
        color: white !important;
    }}
    
    /* Style the file uploader */
    .stFileUploader > div {{
        background-color: rgba(0, 0, 0, 0.8) !important;
        border-radius: 10px;
        padding: 1.5rem;
        border: 2px solid #4CAF50;
        color: white !important;
    }}
    
    .stFileUploader label {{
        color: white !important;
        font-weight: bold !important;
    }}
    
    /* File uploader text */
    .stFileUploader [data-testid="stFileUploadDropzone"] {{
        background-color: rgba(0, 0, 0, 0.6) !important;
        border: 2px dashed #4CAF50 !important;
        color: white !important;
    }}
    
    .stFileUploader [data-testid="stFileUploadDropzone"] p {{
        color: white !important;
    }}
    
    /* Style buttons */
    .stButton > button {{
        background-color: #4CAF50 !important;
        color: white !important;
        border-radius: 8px !important;
        border: 2px solid #4CAF50 !important;
        padding: 0.7rem 1.5rem !important;
        font-weight: bold !important;
        font-size: 16px !important;
        transition: all 0.3s ease !important;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3) !important;
    }}
    
    .stButton > button:hover {{
        background-color: #45a049 !important;
        border-color: #45a049 !important;
        transform: translateY(-2px) !important;
        box-shadow: 0 6px 12px rgba(0, 0, 0, 0.4) !important;
    }}
    
    /* Download button styling */
    .stDownloadButton > button {{
        background-color: #2196F3 !important;
        color: white !important;
        border-radius: 8px !important;
        border: 2px solid #2196F3 !important;
        padding: 0.7rem 1.5rem !important;
        font-weight: bold !important;
        font-size: 14px !important;
        transition: all 0.3s ease !important;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3) !important;
        width: 100% !important;
    }}
    
    .stDownloadButton > button:hover {{
        background-color: #1976D2 !important;
        border-color: #1976D2 !important;
        transform: translateY(-2px) !important;
        box-shadow: 0 6px 12px rgba(0, 0, 0, 0.4) !important;
    }}
    
    /* Style error/success messages */
    .stAlert {{
        background-color: rgba(0, 0, 0, 0.8) !important;
        border-radius: 8px !important;
        border-left: 4px solid #4CAF50 !important;
        color: white !important;
    }}
    
    .stSuccess {{
        background-color: rgba(76, 175, 80, 0.9) !important;
        color: white !important;
        border-radius: 8px !important;
        border: 2px solid #4CAF50 !important;
    }}
    
    .stError {{
        background-color: rgba(244, 67, 54, 0.9) !important;
        color: white !important;
        border-radius: 8px !important;
        border: 2px solid #f44336 !important;
    }}
    
    /* Style spinner */
    .stSpinner > div {{
        border-color: #4CAF50 !important;
    }}
    
    /* Column styling */
    .stColumn {{
        background-color: rgba(0, 0, 0, 0.3) !important;
        border-radius: 10px !important;
        padding: 1rem !important;
    }}
    
    /* Medical Report Display Area Styling */
    .medical-report {{
        background-color: rgba(0, 0, 0, 0.85) !important;
        color: white !important;
        padding: 1.5rem !important;
        border-radius: 10px !important;
        margin: 1rem 0 !important;
        border: 2px solid #4CAF50 !important;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3) !important;
    }}
    
    .medical-report h3 {{
        color: #4CAF50 !important;
        border-bottom: 2px solid #4CAF50 !important;
        padding-bottom: 0.5rem !important;
        margin-bottom: 1rem !important;
    }}
    
    .medical-report p {{
        color: white !important;
        line-height: 1.6 !important;
        margin-bottom: 0.8rem !important;
    }}
    
    /* Success message styling */
    .stSuccess {{
        background-color: rgba(76, 175, 80, 0.9) !important;
        color: white !important;
        border-radius: 5px !important;
    }}
    
    /* Footer styling */
    .footer {{
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: rgba(0, 0, 0, 0.8);
        color: white;
        text-align: center;
        padding: 10px 0;
        font-size: 14px;
        z-index: 999;
        backdrop-filter: blur(5px);
    }}
    
    .footer a {{
        color: #4CAF50;
        text-decoration: none;
        font-weight: bold;
    }}
    
    .footer a:hover {{
        color: #45a049;
        text-decoration: underline;
    }}
    </style>
    '''
    
    st.markdown(page_bg_img, unsafe_allow_html=True)

#config

genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))


#prompt

system_prompt="""
You are an AI Medical Report Assistant specializing in analyzing medical images and generating comprehensive diagnostic reports. Your role is to provide detailed, accurate, and professional medical analysis based on uploaded medical images.

**Instructions for Medical Image Analysis:**

1. **Initial Assessment:**
   - Carefully examine the uploaded medical image (X-ray, CT scan, MRI, ultrasound, etc.)
   - Identify the type of medical imaging modality
   - Note the anatomical region being examined
   - Assess image quality and clarity

2. **Detailed Analysis:**
   - Describe normal anatomical structures visible in the image
   - Identify any abnormalities, lesions, or pathological findings
   - Note size, location, density, and characteristics of any abnormal findings
   - Compare findings with normal anatomical references

3. **Clinical Observations:**
   - Document specific measurements when applicable
   - Describe tissue density, bone alignment, organ positioning
   - Note any signs of inflammation, infection, trauma, or degenerative changes
   - Identify any medical devices or foreign objects visible

4. **Diagnostic Impression:**
   - Provide a preliminary diagnostic impression based on findings
   - List differential diagnoses when appropriate
   - Indicate confidence level in findings
   - Suggest correlation with clinical symptoms if mentioned

5. **Recommendations:**
   - Suggest additional imaging studies if needed
   - Recommend follow-up timeframes
   - Indicate if urgent clinical attention is required
   - Suggest correlation with laboratory results or physical examination

**Report Format:**
- Use professional medical terminology
- Structure the report clearly with headers
- Maintain objectivity and accuracy
- Include disclaimer about AI limitations
- Emphasize the need for physician review

**Important Disclaimers:**
- This analysis is for educational/informational purposes only
- All findings must be verified by a qualified radiologist or physician
- AI analysis should not replace professional medical judgment
- Seek immediate medical attention for emergency situations

Please analyze the uploaded medical image and provide a comprehensive report following these guidelines.
"""


generation_config = {
    "temperature": 1,
    "top_p": 0.95,
    "top_k": 40,
    "max_output_tokens": 8192,
}

safety_settings = [
    {
        "category": "HARM_CATEGORY_HARASSMENT",
        "threshold": "BLOCK_MEDIUM_AND_ABOVE"
    },
    {
        "category": "HARM_CATEGORY_HATE_SPEECH",
        "threshold": "BLOCK_MEDIUM_AND_ABOVE"
    },
    {
        "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
        "threshold": "BLOCK_MEDIUM_AND_ABOVE"
    },
    {
        "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
        "threshold": "BLOCK_MEDIUM_AND_ABOVE"
    }
]


#layout

st.set_page_config(page_title="Diagnostic Analysis", page_icon=":robot_face:")

# Set background image
set_png_as_page_bg('public/Backgroun.jpg')

col1, col2, col3 = st.columns([1, 2, 1])
with col2:
    st.title("Diagnostic Analysis")
    # Uncomment the line below if you have a logo.png file
    # st.image("logo.png", width=200)
    
    
upload_file = st.file_uploader("Please upload medical images for medical report", type=["png", "jpg", "jpeg", "gif", "bmp"])

submit_button = st.button("Generate Image Analysis")

if submit_button:
    if upload_file is not None:
        with st.spinner("Generating Image Analysis..."):
            try:
                # Create the model
                model = genai.GenerativeModel(
                    model_name="gemini-1.5-flash",
                    generation_config=generation_config,
                    safety_settings=safety_settings
                )
                
                # Convert uploaded file to PIL Image
                from PIL import Image
                import io
                
                image = Image.open(io.BytesIO(upload_file.read()))
                
                # Generate response with image
                response = model.generate_content([system_prompt, image])
                
                st.success("Image Analysis Generated Successfully!")
                
                # Display medical report in a dark container
                st.markdown(f"""
                <div class="medical-report">
                    <h3>🏥 Medical Report Analysis</h3>
                    <p>{response.text.replace(chr(10), '<br>')}</p>
                </div>
                """, unsafe_allow_html=True)
                
                # Add PDF download button
                st.markdown("---")
                col1, col2, col3 = st.columns([1, 2, 1])
                with col2:
                    if st.button("📄 Download PDF Report", key="pdf_download"):
                        # Generate PDF
                        current_time = datetime.now().strftime("%Y%m%d_%H%M%S")
                        filename = f"medical_report_{current_time}.pdf"
                        
                        pdf_buffer = generate_pdf_report(
                            response.text, 
                            patient_info=f"Report generated from {upload_file.name}",
                            filename=filename
                        )
                        
                        st.download_button(
                            label="📥 Click to Download PDF",
                            data=pdf_buffer.getvalue(),
                            file_name=filename,
                            mime="application/pdf",
                            key="download_pdf_button"
                        )
                
            except Exception as e:
                st.error(f"An error occurred: {str(e)}")
                st.write("Please check your API key and try again.")
    else:
        st.error("Please upload a medical image file to proceed.")

# Footer
st.markdown("""
<div class="footer">
    <p>🩺 Developed by <strong>Sankalp</strong> | Medical AI Assistant 🤖</p>
</div>
""", unsafe_allow_html=True)