import streamlit as st
from pathlib import Path
import google.generativeai as genai
import base64
import os
from dotenv import load_dotenv
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from io import BytesIO
from datetime import datetime
from PIL import Image

# Load environment variables
load_dotenv()

# --- PDF Generation Function (Slightly modified for clarity) ---
def generate_pdf_report(report_text, patient_info="Anonymous", filename="medical_report.pdf"):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1*inch, bottomMargin=1*inch)
    
    styles = getSampleStyleSheet()
    
    # Custom styles for a professional look
    title_style = ParagraphStyle(
        'CustomTitle', parent=styles['h1'], fontSize=22, textColor=colors.HexColor("#1E90FF"),
        spaceAfter=24, alignment=TA_CENTER, fontName='Helvetica-Bold'
    )
    header_style = ParagraphStyle(
        'CustomHeader', parent=styles['h2'], fontSize=14, textColor=colors.HexColor("#4682B4"),
        spaceBefore=12, spaceAfter=8, fontName='Helvetica-Bold'
    )
    body_style = ParagraphStyle(
        'CustomBody', parent=styles['Normal'], fontSize=11, alignment=TA_JUSTIFY,
        spaceBefore=6, spaceAfter=6, leading=14
    )
    info_style = ParagraphStyle(
        'InfoStyle', parent=styles['Normal'], fontSize=9, textColor=colors.grey,
        alignment=TA_CENTER, spaceBefore=10, spaceAfter=10
    )

    story = []
    
    # Title
    story.append(Paragraph("🏥 AI-Powered Medical Image Analysis", title_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Report Metadata
    current_time = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    story.append(Paragraph(f"Patient Information: {patient_info}", info_style))
    story.append(Paragraph(f"Report Generated On: {current_time}", info_style))
    story.append(Spacer(1, 0.3*inch))
    
    # Process and add report text
    story.append(Paragraph("Detailed Analysis Report", header_style))
    
    paragraphs = report_text.split('\n')
    for para in paragraphs:
        para = para.strip()
        if not para:
            continue
        # Improved logic for detecting headers
        if para.startswith('**') and para.endswith('**'):
            header_text = para.replace('**', '').strip()
            story.append(Paragraph(header_text, header_style))
        else:
            story.append(Paragraph(para, body_style))
        story.append(Spacer(1, 6))
    
    # Footer
    story.append(Spacer(1, 0.5*inch))
    story.append(Paragraph("⚠️ IMPORTANT DISCLAIMER", header_style))
    disclaimer = """
    This report is generated by an AI model and is intended for informational purposes only. 
    It is not a substitute for professional medical diagnosis, advice, or treatment. 
    Always consult with a qualified healthcare provider for any medical concerns or before making any decisions related to your health. 
    All findings must be verified by a licensed physician or radiologist.
    """
    story.append(Paragraph(disclaimer, info_style))
    story.append(Spacer(1, 0.3*inch))
    story.append(Paragraph("Powered by Gemini AI | Developed by Sankalp", info_style))
    
    doc.build(story)
    buffer.seek(0)
    return buffer

# --- UI Styling Functions ---
def get_base64_of_bin_file(bin_file):
    with open(bin_file, 'rb') as f:
        data = f.read()
    return base64.b64encode(data).decode()

def set_page_background(png_file):
    bin_str = get_base64_of_bin_file(png_file)
    page_bg_img = f'''
    <style>
    .stApp {{
        background-image: url("data:image/png;base64,{bin_str}");
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        background-attachment: fixed;
    }}
    
    /* Main content area */
    .main .block-container {{
        padding: 2rem;
        border-radius: 10px;
    }}

    /* Card-like containers */
    .st-emotion-cache-z5fcl4 {{
        background-color: rgba(10, 20, 30, 0.85);
        border: 1px solid rgba(255, 255, 255, 0.2);
        padding: 1.5rem;
        border-radius: 15px;
        backdrop-filter: blur(10px);
        box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);
    }}

    /* Title styling */
    h1 {{
        color: #FFFFFF;
        text-align: center;
        font-weight: bold;
        text-shadow: 2px 2px 8px rgba(0, 0, 0, 0.7);
    }}

    /* Subheader styling for report sections */
    h3 {{
        color: #1E90FF; /* DodgerBlue */
        border-bottom: 2px solid #1E90FF;
        padding-bottom: 5px;
    }}

    /* General text color */
    .st-emotion-cache-1r6slb0, .st-emotion-cache-1y4p8pa, p {{
        color: #E0E0E0;
    }}

    /* Button styling */
    .stButton > button {{
        background-color: #1E90FF;
        color: white;
        border-radius: 8px;
        border: none;
        padding: 10px 24px;
        font-weight: bold;
        transition: all 0.3s ease;
        box-shadow: 0 4px 14px 0 rgba(0, 118, 255, 0.39);
        width: 100%;
    }}
    .stButton > button:hover {{
        background-color: #00BFFF; /* DeepSkyBlue */
        transform: translateY(-2px);
        box-shadow: 0 6px 20px 0 rgba(0, 118, 255, 0.5);
    }}

    /* Download button specific styling */
    .stDownloadButton > button {{
        background-color: #4CAF50; /* A nice green for downloads */
        color: white;
        border-radius: 8px;
        border: none;
        padding: 10px 24px;
        font-weight: bold;
        transition: all 0.3s ease;
        width: 100%;
    }}
    .stDownloadButton > button:hover {{
        background-color: #45a049;
    }}

    /* File uploader styling */
    .stFileUploader {{
        background-color: rgba(255, 255, 255, 0.05);
        border: 1px dashed #1E90FF;
        border-radius: 10px;
        padding: 1rem;
    }}
    
    /* Footer Styling */
    footer {{
        visibility: hidden;
    }}
    .footer {{
        text-align: center;
        padding: 1rem;
        color: rgba(255, 255, 255, 0.7);
    }}
    </style>
    '''
    st.markdown(page_bg_img, unsafe_allow_html=True)

# --- AI Model Configuration ---
try:
    genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))
except Exception as e:
    st.error("API Key not configured. Please set your GOOGLE_API_KEY environment variable.")
    st.stop()

system_prompt="""
You are a specialized AI Medical Assistant. Your task is to analyze medical images (like X-rays, CT scans, MRIs) and generate a comprehensive, professional diagnostic report.

**Report Structure:**
1.  **Image Modality:** Identify the type of scan (e.g., Chest X-ray, Brain MRI).
2.  **Findings:** Detail all observations. Describe normal structures and any abnormalities (lesions, fractures, inflammation). Note their size, location, and characteristics precisely.
3.  **Impression:** Provide a summary of the most critical findings and a potential diagnosis or a list of differential diagnoses.
4.  **Recommendations:** Suggest next steps, such as clinical correlation, follow-up imaging, or specific specialist consultations.

**Guidelines:**
- Use clear, professional medical terminology.
- Structure your response using Markdown for headers (e.g., `**Findings:**`).
- Be objective and base your analysis solely on the visual information in the image.
- **Crucially, end every report with the following disclaimer:**
  `---`
  `**Disclaimer:** This AI-generated analysis is for informational purposes only and is not a substitute for professional medical advice. A qualified healthcare professional must verify all findings.`
"""

generation_config = {"temperature": 0.8, "top_p": 0.95, "top_k": 40, "max_output_tokens": 8192}

safety_settings = [
    {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
    {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
    {"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
    {"category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_MEDIUM_AND_ABOVE"}
]

model = genai.GenerativeModel(
    model_name="gemini-1.5-flash",
    generation_config=generation_config,
    safety_settings=safety_settings
)

# --- Streamlit App Layout ---
st.set_page_config(page_title="AI Medical Report Analyzer", page_icon="🩺", layout="wide")
#set_page_background('public/Background.png')

# Initialize session state
if 'report_generated' not in st.session_state:
    st.session_state.report_generated = False
    st.session_state.analysis_text = ""
    st.session_state.uploaded_image = None
    st.session_state.patient_info = "Anonymous"

# --- Main App Interface ---
st.title("🩺 AI Medical Report Analyzer")
st.markdown("<p style='text-align: center; color: #BBBBBB;'>Upload a medical image to receive an AI-powered analysis. For educational and informational use only.</p>", unsafe_allow_html=True)
st.markdown("---")

with st.container():
    patient_name = st.text_input("Enter Patient Name or ID (Optional)", placeholder="e.g., John Doe, Patient #12345")
    uploaded_file = st.file_uploader("Choose a medical image...", type=["png", "jpg", "jpeg", "bmp", "gif"])
    
    submit_button = st.button("Generate Analysis Report")

    if submit_button:
        if uploaded_file is not None:
            with st.spinner("Analyzing image... This may take a moment."):
                try:
                    image_bytes = uploaded_file.getvalue()
                    image = Image.open(BytesIO(image_bytes))
                    
                    response = model.generate_content([system_prompt, image])
                    
                    # Update session state
                    st.session_state.report_generated = True
                    st.session_state.analysis_text = response.text
                    st.session_state.uploaded_image = image_bytes
                    st.session_state.patient_info = patient_name if patient_name else f"Report from {uploaded_file.name}"
                    
                    st.success("Analysis Complete!")
                except Exception as e:
                    st.error(f"An error occurred during analysis: {e}")
        else:
            st.warning("Please upload an image file before generating the analysis.")

# --- Display Results Section ---
if st.session_state.report_generated:
    st.markdown("---")
    
    col1, col2 = st.columns([1, 1.5]) # Create two columns

    with col1:
        st.subheader("Uploaded Medical Image")
        st.image(st.session_state.uploaded_image, caption="Patient Scan", use_column_width=True)

    with col2:
        st.subheader("AI-Generated Analysis")
        st.markdown(st.session_state.analysis_text)
        
        # Generate PDF in memory
        pdf_buffer = generate_pdf_report(
            st.session_state.analysis_text,
            patient_info=st.session_state.patient_info
        )
        current_time = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"Medical_Report_{current_time}.pdf"

        # Add the download button
        st.download_button(
            label="📄 Download Full Report (PDF)",
            data=pdf_buffer,
            file_name=filename,
            mime="application/pdf",
            key="download_pdf"
        )

# --- Footer ---
st.markdown("---")
st.markdown("""
<div class="footer">
    <p>Developed by <strong>Sankalp</strong> | This is a demonstration tool and not for clinical use.</p>
</div>
""", unsafe_allow_html=True)