import jsPDF from 'jspdf';

interface PDFOptions {
  reportText: string;
  patientInfo: string;
}

export function generatePDF({ reportText, patientInfo }: PDFOptions): Blob {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 25;
  const maxWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  // Title
  doc.setFontSize(22);
  doc.setTextColor(30, 144, 255);
  doc.text('🏥 AI-Powered Medical Image Analysis', pageWidth / 2, yPosition, {
    align: 'center',
  });
  yPosition += 15;

  // Date and Patient Info
  doc.setFontSize(9);
  doc.setTextColor(128, 128, 128);
  const currentDate = new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
  doc.text(`Patient Information: ${patientInfo}`, pageWidth / 2, yPosition, {
    align: 'center',
  });
  yPosition += 6;
  doc.text(`Report Generated On: ${currentDate}`, pageWidth / 2, yPosition, {
    align: 'center',
  });
  yPosition += 15;

  // Section Header
  doc.setFontSize(14);
  doc.setTextColor(70, 130, 180);
  doc.text('Detailed Analysis Report', margin, yPosition);
  yPosition += 10;

  // Process report text
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);

  const lines = reportText.split('\n');
  
  lines.forEach((line) => {
    const trimmedLine = line.trim();
    if (!trimmedLine) {
      yPosition += 4;
      return;
    }

    // Check if we need a new page
    if (yPosition > pageHeight - margin - 20) {
      doc.addPage();
      yPosition = margin;
    }

    // Handle headers (marked with **)
    if (trimmedLine.startsWith('**') && trimmedLine.endsWith('**')) {
      doc.setFontSize(12);
      doc.setTextColor(70, 130, 180);
      const headerText = trimmedLine.replace(/\*\*/g, '');
      doc.text(headerText, margin, yPosition);
      yPosition += 8;
      doc.setFontSize(11);
      doc.setTextColor(0, 0, 0);
    } else {
      // Regular text
      const splitText = doc.splitTextToSize(trimmedLine, maxWidth);
      doc.text(splitText, margin, yPosition);
      yPosition += splitText.length * 6;
    }
  });

  // Add disclaimer at the bottom
  if (yPosition > pageHeight - margin - 60) {
    doc.addPage();
    yPosition = margin;
  }

  yPosition += 10;
  doc.setFontSize(12);
  doc.setTextColor(70, 130, 180);
  doc.text('⚠️ IMPORTANT DISCLAIMER', margin, yPosition);
  yPosition += 8;

  doc.setFontSize(9);
  doc.setTextColor(128, 128, 128);
  const disclaimer =
    'This report is generated by an AI model and is intended for informational purposes only. ' +
    'It is not a substitute for professional medical diagnosis, advice, or treatment. ' +
    'Always consult with a qualified healthcare provider for any medical concerns or before making any decisions related to your health. ' +
    'All findings must be verified by a licensed physician or radiologist.';

  const disclaimerLines = doc.splitTextToSize(disclaimer, maxWidth);
  doc.text(disclaimerLines, margin, yPosition);
  yPosition += disclaimerLines.length * 5 + 10;

  doc.text('Powered by Gemini AI | Developed by Sankalp', pageWidth / 2, yPosition, {
    align: 'center',
  });

  return doc.output('blob');
}
